name = "tony starch";
console.log(name);
isFollow = true;
console.log(isFollow);
isPassword = false;
console.log(isPassword);
let fullName = "tony starch";
let age = 30;
console.log(fullName);
console.log(age);
let age = 23;
age = 24;
age = 25;
console.log(age);
constPI = 3.14;
console.log(constPI);
let a ;
console.log(a);
